version: "3.9"
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '40:40'
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: develop,debug
            SAIL_XDEBUG_CONFIG: "client_host=127.0.0.1"
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
    web:
        image: firsabila/laravel-8
        ports: 
          - "8181:8181"
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
    

networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local